deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 2.7
    repo: DmytroLitvinov/kuna
    tags: true
  user: DmytroLitvinov
  password:
    secure: k6Nx18djQoJfJ6MDgCtIDiFtHGdoxa133FuVU2teBcxqlnaWfV3uAAVxnF9VORQT8qpg+OKQMla5dwuPVb69IUyA//PMKe+XVF6LAmUrbB+WishGWgMEKfUn7KV3+/84Nr3JzLQwsh51tJ0jmdRjdd4/EUWLIx2LXb5F4UvHL6XA6sXkGsMG9w7WS2TzURubXVzM2/caxtuJnw7Gk9aAeaq/vh97hsip52iOZCSAkM//JKu7KjTNcDjXFAdhI3alBOfZqe/NvaT+tr53o4yEcZiRWsaifD/cOANuzFOYowh08eUB17jGAKaPIkGb0B8FAWsmxq7w9dI0u7itA6XZvTlzVLd4O3JWowtcXjCDojqoAMXleIA/ClB6NEKijczFgYQXwGGr3/tL+U2Lx4uimXHdOogg0l2JBRIyvNq41LiByxq06uo2UBXzNCEA0ah+NLJvtfy/GwN+XDrv11Y6geGjDUabp1RY8KDg/0qMx7lE++8wP6FAJrCRCBgDY3JkwsG36eVieMG7vYenc3TXUsSc7zmsltN1jFaMcu/Y9X4AIkKYAhVd0CrxR7IZUvFXQaGSYpji5NyTBoCvWz23d7F8DPiiA60rRF65kagzEtVuFv6XQT/1pHtjjW0zugV1vdGGQYoBBKdz5PPzOTRb94MZXjuzanhqrVQ+It7qCGY=
install: pip install -U tox-travis
language: python
python:
- 3.6
- 3.5
- 2.7
script: tox
